theme: jekyll-theme-minimal
title: Aggrey Muhebwa <br>
description: <br> [UN-IPCC](https://www.ipcc.ch/) scholar, an [e-GUIDE](https://eguide.io/) fellow and part of [DAWG](https://swot.jpl.nasa.gov/documents/4050/) | Ph.D Student <br><br> Contact:<a href="mailto:muhebwa.grey@gmail.com"> amuhebwa at umass dot edu</a>.
logo: /img/avatar.png
auto_ids: true
