theme: jekyll-theme-minimal
title: Aggrey Muhebwa <br>
description: <br> Research Scientist | Machine Learning | Remote Sensing.<br><br> Contact:<a href="mailto:muhebwa.grey@gmail.com"> amuhebwa at umass dot edu</a>. <br>
I sometimes share my not so smart thoughts on Twitter :<a href="https://twitter.com/m_aggrey"> @m_aggrey</a>.
logo: /img/avatar.png
auto_ids: true
