remote_theme: simplex-design/jekyll-theme-simplex
#remote_theme: yous/whiteglass
# title: Aggrey Muhebwa, PhD <br>
title: Aggrey Muhebwa, PhD
# description: <br> Postdoc | Ex UN-IPCC scholar | e-GUIDE fellow | Member of DAWG <br><br> Contact:<a href="mailto:muhebwa.grey@gmail.com"> amuhebwa at stanford dot edu</a>.
logo: /img/avatar.png
# auto_ids: true
