remote_theme: h-enk/doks
# remote_theme: just-the-docs/just-the-docs
#remote_theme: pages-themes/slate@v0.2.0
#theme:jekyll-theme-minimal
# title: Aggrey Muhebwa, PhD <br>
title: Aggrey Muhebwa, PhD
# description: <br> Postdoc | Ex UN-IPCC scholar | e-GUIDE fellow | Member of DAWG <br><br> Contact:<a href="mailto:muhebwa.grey@gmail.com"> amuhebwa at stanford dot edu</a>.
logo: /img/avatar.png
# auto_ids: true
